In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print("\n Type of the element \n",a.dtype)
print("\n Shape of the array\n",a.shape)
print('\n size of the array\n',a.size)
new=a[::-1]
print("\n Reversed array\n",new)
slic=a[2:5]
print('\n sliced array:\n ',slic)
ne=a>7
newarray=a[ne]
print("\n The array element which are all greater than :\n",newarray)


 Type of the element 
 int32

 Shape of the array
 (10,)

 size of the array
 10

 Reversed array
 [10  9  8  7  6  5  4  3  2  1]

 sliced array:
  [3 4 5]

 The array element which are all greater than :
 [ 8  9 10]
