In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [2]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)
flat=arr.flatten()
print(flat)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1=np.zeros((5,3))
print("\nArray of Zero values\n",arr1)
new=np.random.random((3,5))
print("\nArray of random values\n",new)
new1=np.arange(0,9,1)
print("\n Range values\n",new1)
new2=arr.reshape((3,3))
print("\nReshaped Array\n",new2)
print("\n No of Dimensions :",arr.ndim)



Array of Zero values
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of random values
 [[0.51214013 0.80335332 0.06166103 0.91908388 0.43602359]
 [0.42586617 0.7350237  0.40847096 0.91330847 0.96490179]
 [0.15697433 0.00118472 0.36727874 0.28159416 0.5598218 ]]

 Range values
 [0 1 2 3 4 5 6 7 8]

Reshaped Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 No of Dimensions : 2


In [10]:
#Shape Of The Array
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n Shape of Array:\n",arr.shape)
    


 Shape of Array:
 (3, 3)


In [1]:
#size of the array
import numpy as np
arr=np.array([1,2,3,4,5])
print("\n Array element type\n",arr.dtype)


 Array element type
 int32


In [2]:
#convert interger into float
import numpy as np
arr=np.array([1,2,3,4,5])
newtype=arr.astype('f')
print("\n convert array element\n",newtype)
print("converted array:",newtype.dtype)


 convert array element
 [1. 2. 3. 4. 5.]
converted array: float32


In [5]:
#size of the array

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("\n Size of array\n",arr.size)


 Size of array
 10
