In [9]:
#slicing 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[2:5]
print(slice)

[3 4 5]


In [10]:
#slicing with step of 2 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::2]
print(slice)


[1 3 5 7 9]


In [11]:
#reverse the array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
reverse=arr[::-1]
print(reverse)

[9 8 7 6 5 4 3 2 1]


In [13]:
#slicing multidimensional array
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice row 0 to 2 column 1 to 3
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [21]:
#extract first row
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
new=arr[0,:]
print(new)
r=arr[2,:]
print(r)
print(arr[0,0])
print(arr[1,2])

[1 2 3]
[7 8 9]
1
6


In [23]:
#basic array indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1])
#negative indexing
print(arr[-1])

20
50


In [25]:
#subset indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])


[20 30 40]


In [27]:
#index the element that meet the condition
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])


[30 40 50]


In [30]:
#horizontal joints combines data by adding elements side by side
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
#depth joints combines data by adding elements side by side
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [36]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
#split array into three equal parts
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5])
#split array into three unequal parts
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
